### ISSUE TITLE
Investigate how we can connect with MongoDB to ask for updates

### ISSUE THREAD

**Issue by nachocano** [googleinterns/knative-source-mongodb#5]
**Problem**
We need to understand how to connect with mongodb using credentials, and how we can subscribe to notifications or changes updates.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
Understand how from the data plane we will be able to pull updates from Mongo.

**Additional context (optional)**
Example from CouchDB https://github.com/knative/eventing-contrib/blob/master/couchdb/source/pkg/adapter/adapter.go

**Comment by selim5** [comment]
## First steps:  Try to programmatically listen for a change

### Need to deploy a container that runs main in go 
- (example in knative-gcp/test/)
- Make a experimental folder in repo

**Comment by selim5** [comment]
Managed to listen for change on a Replica-Set (turns out standalone cannot use Watch Stream which is used to watch for changes)

![image](https://user-images.githubusercontent.com/20800119/86489949-cee02800-bd33-11ea-82ac-d98541d8ddb1.png)

Additional info:
How to specify what kind of event to listen to (example available at https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo?tab=doc#Collection.Watch )

**Comment by selim5** [comment]
Managed to listen for change on a Replica-Set (turns out standalone cannot use Watch Stream which is used to watch for changes)

![image](https://user-images.githubusercontent.com/20800119/86489949-cee02800-bd33-11ea-82ac-d98541d8ddb1.png)

Additional info:
How to specify what kind of event to listen to (example available at https://pkg.go.dev/go.mongodb.org/mongo-driver/mongo?tab=doc#Collection.Watch )

**Comment by selim5** [comment]
- Any change can be listened to
- Implemented listening to changes using asynchronous go routines https://developer.mongodb.com/quickstart/golang-change-streams

### Example of Insert, Delete, Update
![image](https://user-images.githubusercontent.com/20800119/86516597-f268a880-bdef-11ea-89c0-e8ab4f56e217.png)

### Help/Ressources:
Asynchronous programming in go https://medium.com/@gauravsingharoy/asynchronous-programming-with-go-546b96cd50c1

**Comment by selim5** [comment]
### Next Step
Figure out how to filter changes/extract type of change
